/* ═══════════════════════════════════════════════════════════
   Pine Opti — Base de datos de perfiles de juego offline
   Tweaks específicos por juego, anti-cheats y configuraciones
═══════════════════════════════════════════════════════════ */

export const GAMES = [
  {
    id: "free-fire",
    name: "Free Fire",
    engine: "BlueStacks 5 / MSI App Player",
    genre: "Battle Royale",
    anticheat: ["BlackBox", "Garena Anti-Cheat", "KellerSS"],
    color: "#FF6B35",
    icon: "🔥",
    banner: "https://upload.wikimedia.org/wikipedia/en/3/35/Free_Fire_official_logo.png",
    logo: "https://upload.wikimedia.org/wikipedia/en/3/35/Free_Fire_official_logo.png",
    description: "Free Fire NO tiene cliente nativo para PC. Se ejecuta a través de BlueStacks 5 o MSI App Player (basado en BlueStacks). Los tweaks van orientados al emulador Android, no a un .exe del juego directamente.",
    fps_target: "60-90+",
    resolution: "1280x720 – 1920x1080",
    tweaks: [
      "BlackBox (anti-cheat Garena): NUNCA modificar",
      "Usar BlueStacks 5 o MSI App Player — NO versiones antiguas (BS4 genera más lag)",
      "BlueStacks → Configuración → Rendimiento → Alto rendimiento",
      "Núcleos CPU asignados a BS: 4 o más (máximo disponible)",
      "RAM asignada a BlueStacks: mínimo 4096 MB (ideal 6144)",
      "Motor gráfico BlueStacks → OpenGL (más estable) o Vulkan (más FPS en RTX)",
      "DPI BlueStacks → 240 para mejor detección de Hit-Reg",
      "FPS en Free Fire → 90 si el emulador lo soporta",
      "Desactivar grabación automática de BlueStacks (ahorra CPU)",
      "Plan de energía Windows → Alto rendimiento siempre que corra BS",
      "Nagle Algorithm → Off para menor ping al servidor Garena",
      "Región de servidor → seleccionar el más cercano geográficamente",
      "DNS → 1.1.1.1 Cloudflare para menor ping",
      "Cerrar Chrome y apps pesadas antes de lanzar BlueStacks",
    ],
    settings: [
      { key: "Emulador", value: "BlueStacks 5 / MSI" },
      { key: "CPU asignada", value: "4+ núcleos" },
      { key: "RAM asignada", value: "4096-6144 MB" },
      { key: "Motor gráfico", value: "OpenGL o Vulkan" },
      { key: "FPS en juego", value: "90 (si disponible)" },
      { key: "Sombras in-game", value: "Desactivadas" },
    ],
    expectedFpsGain: "+20-35 FPS",
    protected: ["BlackBox.exe", "GarenaWrapper.dll", "HD-Player.exe", "KellerSS.sys", "KellerSS.dll"],
  },
  {
    id: "cs2",
    name: "Counter-Strike 2",
    engine: "Source 2",
    genre: "FPS Competitivo",
    anticheat: ["VAC", "VACNet"],
    color: "#DE9B35",
    icon: "💣",
    banner: "https://cdn.akamai.steamstatic.com/steam/apps/730/header.jpg",
    logo: "https://cdn.cloudflare.steamstatic.com/steamcommunity/public/images/apps/730/69f7ebe2735c366c65c0b33dae00e12dc40edbe4.jpg",
    description: "El FPS competitivo más popular. CS2 en Source 2 es muy exigente con el CPU. Prioriza frecuencia de CPU sobre núcleos.",
    fps_target: "300+",
    resolution: "1920x1080 o 1280x960 estirado",
    tweaks: [
      "launch options: -freq 240 -tickrate 128 -nojoy -novid",
      "Prioridad cs2.exe → Alta",
      "Desactivar V-Sync en juego y driver",
      "HAGS → Activado para menos frame times",
      "Modo bajo consumo GPU → Desactivado",
      "cl_interp 0 · cl_interp_ratio 1 (conexión estable)",
      "rate 786432 (fibra) o 196608 (cable)",
      "net_maxroutable 1200",
      "Timer Resolution → 0.5ms",
      "Nagle Algorithm → Off",
      "CPU parking → 100% (núcleos siempre activos)",
      "Power plan → Ultimate Performance",
    ],
    settings: [
      { key: "Calidad Global", value: "Low (más FPS)" },
      { key: "Modelo/Textura", value: "Low" },
      { key: "Anti-Aliasing", value: "Desactivado" },
      { key: "FXAA", value: "Desactivado" },
      { key: "V-Sync", value: "Desactivado" },
    ],
    expectedFpsGain: "+30-60 FPS",
    protected: ["steamservice.exe", "csgo.exe"],
  },
  {
    id: "valorant",
    name: "Valorant",
    engine: "Unreal Engine 4",
    genre: "FPS Táctico",
    anticheat: ["Vanguard (Ring 0)"],
    color: "#FF4655",
    icon: "⚡",
    banner: "https://upload.wikimedia.org/wikipedia/en/thumb/7/78/Valorant_cover_art.jpg/460px-Valorant_cover_art.jpg",
    logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/f/fc/Valorant_logo_-_pink.svg/320px-Valorant_logo_-_pink.svg.png",
    description: "FPS táctico de Riot. Vanguard opera a nivel kernel — NUNCA se modifica. Muy CPU-dependiente.",
    fps_target: "240+",
    resolution: "1920x1080 o 1280x960",
    tweaks: [
      "Vanguard: INTOCABLE — operación kernel-level",
      "launch: +fullscreen -nojoy -nosteam",
      "Prioridad VALORANT-Win64-Shipping.exe → Alta",
      "Afinidad CPU → todos los núcleos",
      "FSR/DLSS según GPU disponible",
      "Eliminar NVIDIA GeForce Overlay",
      "Sombras → Off · Bloom → Off",
      "Timer Resolution → 0.5ms",
      "HAGS → Activado (Win10 2004+)",
      "Network Buffering → Minimum",
      "Modo pantalla → Fullscreen exclusivo",
      "V-Sync → Desactivado siempre",
    ],
    settings: [
      { key: "Calidad Material", value: "Low" },
      { key: "Calidad Textura", value: "Low" },
      { key: "Calidad Detalle", value: "Low" },
      { key: "Sombras", value: "Desactivadas" },
      { key: "Anti-Aliasing", value: "MSAA x2 (balance)" },
    ],
    expectedFpsGain: "+25-45 FPS",
    protected: ["vgc.exe", "vgtray.exe", "vgk.sys"],
  },
  {
    id: "fortnite",
    name: "Fortnite",
    engine: "Unreal Engine 5",
    genre: "Battle Royale",
    anticheat: ["Easy Anti-Cheat"],
    color: "#9B59FF",
    icon: "🌩️",
    banner: "https://upload.wikimedia.org/wikipedia/en/thumb/b/bb/Fortnite_cover_art.jpg/460px-Fortnite_cover_art.jpg",
    logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/7/7c/Fortnite_F_lettermark_logo.png/200px-Fortnite_F_lettermark_logo.png",
    description: "Battle Royale con el motor más demandante de la lista. UE5 con Nanite y Lumen. Muy GPU-intensivo.",
    fps_target: "60-144+",
    resolution: "1920x1080 – 2560x1440",
    tweaks: [
      "EasyAntiCheat.exe: INTOCABLE",
      "Renderizado DirectX 12 para hardware reciente",
      "DirectX 11 en GPUs GTX 1660 o anteriores",
      "DLSS Quality en NVIDIA RTX",
      "FSR en AMD o tarjetas sin DLSS",
      "GPU Boost → Activado",
      "RAM: mínimo 16GB para sin stutters",
      "Prioridad FortniteClient-Win64-Shipping.exe → Alta",
      "Windows Shader Preloading → Off (causa stutters)",
      "Resolución 3D → 100%",
      "Motion Blur → Desactivado",
      "Ray Tracing → Off en GPUs mid-range",
    ],
    settings: [
      { key: "Calidad 3D", value: "Low · Res 3D 100%" },
      { key: "Sombras", value: "Desactivadas" },
      { key: "Efectos", value: "Low" },
      { key: "Post-Procesado", value: "Low" },
      { key: "DLSS/FSR", value: "Activado si disponible" },
    ],
    expectedFpsGain: "+15-30 FPS",
    protected: ["EasyAntiCheat.exe", "EasyAntiCheat_EOS.exe"],
  },
  {
    id: "apex",
    name: "Apex Legends",
    engine: "Source Engine (modificado)",
    genre: "Battle Royale",
    anticheat: ["Easy Anti-Cheat"],
    color: "#CD4B3B",
    icon: "💥",
    banner: "https://cdn.akamai.steamstatic.com/steam/apps/1172470/header.jpg",
    logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/43/Apex_legends_simple_logo.svg/240px-Apex_legends_simple_logo.svg.png",
    description: "Battle Royale del Source Engine. Muy CPU-dependiente. Beneficia enormemente de +performance en CPU single-thread.",
    fps_target: "144+",
    resolution: "1920x1080",
    tweaks: [
      "EAC: NUNCA modificar",
      "launch: +fps_max 144 +cl_showfps 4",
      "Limitador FPS en juego (no RTSS para menos latencia)",
      "Prioridad r5apex.exe → Alta",
      "Adaptive Resolution FPS Target → 0 (off)",
      "Streaming Budget → Max",
      "Spot Shadow Detail → Bajo",
      "Dynamic Spot Shadows → Desactivado",
      "Ambient Occlusion → Desactivado",
      "TSAA Anti-Aliasing → Desactivado",
      "Texture Streaming Budget → 4 GB si hay VRAM suficiente",
    ],
    settings: [
      { key: "Texturas de Modelo", value: "Low-Medium" },
      { key: "Efectos", value: "Low" },
      { key: "Sombras", value: "Low" },
      { key: "Anti-Aliasing", value: "Desactivado" },
      { key: "Ambient Occlusion", value: "Desactivado" },
    ],
    expectedFpsGain: "+20-40 FPS",
    protected: ["EasyAntiCheat.exe"],
  },
  {
    id: "pubg",
    name: "PUBG: Battlegrounds",
    engine: "Unreal Engine 4",
    genre: "Battle Royale",
    anticheat: ["BattlEye"],
    color: "#E8A400",
    icon: "🪖",
    banner: "https://cdn.akamai.steamstatic.com/steam/apps/578080/header.jpg",
    logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/39/Pubgmobile_logo.png/240px-Pubgmobile_logo.png",
    description: "El Battle Royale original. UE4 muy GPU-intensivo. BattlEye protegido. Se beneficia de GPU settings.",
    fps_target: "60-120+",
    resolution: "1920x1080",
    tweaks: [
      "BEService: INTOCABLE",
      "Renderizado DirectX 12",
      "Prioridad TslGame.exe → Alta",
      "Shadows → Very Low o Ultra Low",
      "Efectos → Low",
      "Distancia de vista → Medium (mucho impacto)",
      "PostProcessing → Very Low",
      "Anti-Aliasing → Desactivado",
      "HAGS → Activado",
      "GPU Overclocking leve (+5-10%) para más headroom",
      "Anti-Aliasing → TAA si se quiere suavidad",
    ],
    settings: [
      { key: "Renderizado", value: "100% · DX12" },
      { key: "Anti-Aliasing", value: "Desactivado" },
      { key: "Distancia Vista", value: "Medium" },
      { key: "Sombras", value: "Very Low" },
      { key: "Efectos", value: "Low" },
    ],
    expectedFpsGain: "+15-25 FPS",
    protected: ["BEService.exe", "BattlEye.dll"],
  },
  {
    id: "lol",
    name: "League of Legends",
    engine: "Riot Engine",
    genre: "MOBA",
    anticheat: ["Vanguard (Ring 0)"],
    color: "#C69B3A",
    icon: "⚔️",
    banner: "https://upload.wikimedia.org/wikipedia/en/thumb/1/1a/League_of_Legends_cover.jpg/460px-League_of_Legends_cover.jpg",
    logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d8/League_of_Legends_2019_vector.svg/240px-League_of_Legends_2019_vector.svg.png",
    description: "El MOBA más popular. Vanguard activo desde 2023. Muy poco exigente en hardware pero latencia crítica.",
    fps_target: "144+",
    resolution: "1920x1080",
    tweaks: [
      "Vanguard: NUNCA MODIFICAR",
      "Frame Rate Cap → 144 o 240 según monitor",
      "Resolución → 1920x1080 nativo",
      "Calidad de carácter → High (poca GPU extra)",
      "Efectos → Medium",
      "Nagle Algorithm → Off (crítico para ping)",
      "DNS → Cloudflare 1.1.1.1",
      "Servidor de juego correcto (EUW/NA/LAN)",
      "Procesos en background → Cerrar todos",
      "Timer Resolution → 0.5ms",
      "Modo pantalla → Fullscreen exclusivo",
    ],
    settings: [
      { key: "Resolución", value: "1920×1080 Nativo" },
      { key: "Carácter Quality", value: "High" },
      { key: "Sombras", value: "Medium" },
      { key: "Efectos", value: "Medium" },
      { key: "Frame Cap", value: "144 / 240" },
    ],
    expectedFpsGain: "+10-20 FPS",
    protected: ["vgc.exe", "vgtray.exe", "vgk.sys"],
  },
  {
    id: "cod",
    name: "Call of Duty: Warzone",
    engine: "IW Engine 8",
    genre: "Battle Royale",
    anticheat: ["Ricochet (Kernel)"],
    color: "#3A9E44",
    icon: "🔫",
    banner: "https://cdn.akamai.steamstatic.com/steam/apps/1938090/header.jpg",
    logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/6e/Call_of_Duty_logo.svg/240px-Call_of_Duty_logo.svg.png",
    description: "Battle Royale de Activision. Anti-cheat Ricochet nivel kernel desde 2021. GPU muy intensivo.",
    fps_target: "60-120+",
    resolution: "1920x1080",
    tweaks: [
      "Ricochet (cod_kernel.sys): INTOCABLE",
      "Texture Resolution → Low para + VRAM libre",
      "Shadow Map Resolution → Low",
      "Particle Quality → Low",
      "On-Demand Texture Streaming → Desactivado",
      "Bullet Impacts → Desactivado",
      "Field of View → 90-105 (balance)",
      "DLSS/FSR/XeSS según GPU",
      "Render Resolution → 100%",
      "V-Sync → Desactivado siempre",
      "Motion Blur → Desactivado (crítico para claridad)",
      "NVIDIA Reflex → Activado + Boost",
    ],
    settings: [
      { key: "Texturas", value: "Low (liberar VRAM)" },
      { key: "Sombras", value: "Low" },
      { key: "DLSS/FSR", value: "Quality si disponible" },
      { key: "V-Sync", value: "Desactivado" },
      { key: "Motion Blur", value: "Desactivado" },
    ],
    expectedFpsGain: "+20-35 FPS",
    protected: ["cod_kernel.sys", "cod.exe"],
  },
  {
    id: "roblox",
    name: "Roblox",
    engine: "Roblox Engine",
    genre: "Metaverso / Juegos",
    anticheat: ["Hyperion (Byfron)"],
    color: "#E8271A",
    icon: "🧱",
    banner: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4e/Roblox_Logo_2022.png/460px-Roblox_Logo_2022.png",
    logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4e/Roblox_Logo_2022.png/200px-Roblox_Logo_2022.png",
    description: "Plataforma de juegos de Roblox. Hyperion anti-cheat activo. Muy bajo en requisitos pero sensible a latencia.",
    fps_target: "60+",
    resolution: "1920x1080",
    tweaks: [
      "Hyperion (RobloxPlayerLauncher): NUNCA modificar",
      "Shift Lock para control más preciso",
      "Render Distance según servidor",
      "Graphics Quality → Nivel 5-7 (balance)",
      "Fullscreen > Windowed para menos input lag",
      "Nagle → Off (ping más estable)",
      "DNS Cloudflare 1.1.1.1",
      "Cerrar Discord overlay durante Roblox",
      "Prioridad RobloxPlayerBeta.exe → Normal (no alta)",
      "Zona horaria = misma que el servidor del juego",
      "Limpiar caché de Roblox regularmente",
    ],
    settings: [
      { key: "Calidad Gráfica", value: "Nivel 6 / 10" },
      { key: "Modo pantalla", value: "Fullscreen" },
      { key: "Frame Rate Cap", value: "60 o 120" },
      { key: "Render Distance", value: "Según CPU" },
      { key: "V-Sync", value: "Desactivado" },
    ],
    expectedFpsGain: "+15-30 FPS",
    protected: ["RobloxPlayerLauncher.exe", "RobloxCrashHandler.exe"],
  },
  {
    id: "rainbow6",
    name: "Rainbow Six Siege",
    engine: "AnvilNext 2.0",
    genre: "FPS Táctico",
    anticheat: ["BattlEye"],
    color: "#0A74DA",
    icon: "🌈",
    banner: "https://cdn.akamai.steamstatic.com/steam/apps/359550/header.jpg",
    logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e7/Rainbow_Six_Siege_logo.svg/240px-Rainbow_Six_Siege_logo.svg.png",
    description: "FPS táctico de Ubisoft. Muy CPU-intensivo. BattlEye activo. La latencia es crítica — prioriza red y DNS.",
    fps_target: "144+",
    resolution: "1920x1080",
    tweaks: [
      "BEService.exe: INTOCABLE",
      "Render Scaling → 100%",
      "LOD Quality → Low para más FPS",
      "Shadow Quality → Low",
      "Ambient Occlusion → Desactivado",
      "Lens Flare → Desactivado",
      "Anti-Aliasing → T-AA",
      "Prioridad RainbowSix.exe → Alta",
      "DNS → Cloudflare 1.1.1.1",
      "Nagle Algorithm → Off",
      "Ubisoft Connect overlay → Desactivado",
    ],
    settings: [
      { key: "Calidad Textura", value: "Medium" },
      { key: "Sombras", value: "Low" },
      { key: "Anti-Aliasing", value: "T-AA" },
      { key: "LOD Quality", value: "Low" },
      { key: "Lens Effects", value: "Desactivado" },
    ],
    expectedFpsGain: "+25-45 FPS",
    protected: ["BEService.exe", "BattlEye.dll"],
  },
  {
    id: "dota2",
    name: "Dota 2",
    engine: "Source 2",
    genre: "MOBA",
    anticheat: ["VAC"],
    color: "#B01414",
    icon: "🗡️",
    banner: "https://cdn.akamai.steamstatic.com/steam/apps/570/header.jpg",
    logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/ef/Dota2_logo_symbol.png/240px-Dota2_logo_symbol.png",
    description: "MOBA de Valve en Source 2. VAC activo. Muy pesado en CPU en teamfights. Latencia crítica.",
    fps_target: "144+",
    resolution: "1920x1080",
    tweaks: [
      "VAC: NUNCA manipular",
      "launch: -high -nod3d9ex -nosteam",
      "Shader Pre-Caching → Desactivado",
      "Prioridad dota2.exe → Alta",
      "Render Quality → Low-Medium",
      "Shadow Quality → Low o Desactivado",
      "Ambient Creatures → Desactivado",
      "Grass → Desactivado",
      "Timer Resolution → 0.5ms",
      "DNS → Cloudflare para menor ping",
      "Specular → Desactivado para más FPS",
    ],
    settings: [
      { key: "Render Quality", value: "Low" },
      { key: "Sombras", value: "Desactivadas" },
      { key: "Hierba", value: "Desactivada" },
      { key: "Anti-Aliasing", value: "Desactivado" },
      { key: "Efectos", value: "Low" },
    ],
    expectedFpsGain: "+20-40 FPS",
    protected: ["steamservice.exe"],
  },
  {
    id: "gta5",
    name: "GTA V / Online",
    engine: "RAGE Engine",
    genre: "Open World",
    anticheat: ["Rockstar Anti-Cheat"],
    color: "#00B712",
    icon: "🚗",
    banner: "https://cdn.akamai.steamstatic.com/steam/apps/271590/header.jpg",
    logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/8e/GTAV_Official_Logo.png/240px-GTAV_Official_Logo.png",
    description: "Open world de Rockstar. GTA Online muy exigente con RAM y red. Anti-cheat propio. VRAM crítica.",
    fps_target: "60-120+",
    resolution: "1920x1080",
    tweaks: [
      "Anti-cheat Rockstar: NUNCA modificar GTA5.exe core",
      "MSAA → Desactivado (mucho impacto GPU)",
      "Reflection Quality → Low",
      "Shadow Quality → Normal",
      "Population Density → Low",
      "Extended Distance Scaling → Low",
      "Shader Quality → Normal",
      "Prioridad GTA5.exe → Alta",
      "RAM: 16GB+ recomendado para GTA Online",
      "VRAM > 4GB para texturas Very High",
      "In-Game FXAA → Activado (bajo costo)",
      "Grass Quality → Low en GPUs de 4GB VRAM",
    ],
    settings: [
      { key: "MSAA", value: "Desactivado" },
      { key: "FXAA", value: "Activado (bajo costo)" },
      { key: "Sombras", value: "Normal" },
      { key: "Población", value: "Low" },
      { key: "Shader Quality", value: "Normal" },
    ],
    expectedFpsGain: "+20-35 FPS",
    protected: ["GTA5.exe", "PlayGTAV.exe"],
  },
  {
    id: "minecraft",
    name: "Minecraft Java",
    engine: "Java / Fabric / Forge",
    genre: "Sandbox",
    anticheat: ["Server-side (varies)"],
    color: "#5C8D3F",
    icon: "⛏️",
    banner: "https://upload.wikimedia.org/wikipedia/en/thumb/2/27/Minecraft_cover.png/460px-Minecraft_cover.png",
    logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/44/Minecraft_logo_new.png/240px-Minecraft_logo_new.png",
    description: "Sandbox de Mojang. Java Edition muy dependiente del GC de Java. Optimizable con mods y JVM flags.",
    fps_target: "60-240+",
    resolution: "1920x1080",
    tweaks: [
      "Instalar Sodium + Iris (Fabric) para x3 FPS",
      "Usar Azul Zulu JDK 21 (mejor GC que OpenJDK)",
      "JVM flags: -Xms4G -Xmx4G -XX:+UseG1GC",
      "Simulation Distance → 8 chunks (vs 12 default)",
      "Render Distance → 8-10 chunks en PCs medias",
      "Graphics → Fast (no Fancy)",
      "Mipmap Levels → 4",
      "Entity Shadows → Desactivadas",
      "Smooth Lighting → Desactivado",
      "Clouds → Desactivadas",
      "Instalar FerriteCore + Lithium para más optimización",
      "Entity Culling → Activado (Sodium Extra)",
    ],
    settings: [
      { key: "Gráficos", value: "Rápido (Fast)" },
      { key: "Render Distance", value: "8-10 chunks" },
      { key: "Simulation Distance", value: "8 chunks" },
      { key: "Nubes", value: "Desactivadas" },
      { key: "Smooth Lighting", value: "Desactivado" },
    ],
    expectedFpsGain: "+80-200 FPS",
    protected: ["javaw.exe"],
  },
  {
    id: "overwatch2",
    name: "Overwatch 2",
    engine: "Proprietary (Blizzard)",
    genre: "Hero Shooter",
    anticheat: ["Warden (Blizzard)"],
    color: "#FA9C1E",
    icon: "🛡️",
    banner: "https://upload.wikimedia.org/wikipedia/en/thumb/8/82/Overwatch_2.jpg/460px-Overwatch_2.jpg",
    logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/55/Overwatch_circle_logo.svg/240px-Overwatch_circle_logo.svg.png",
    description: "Hero Shooter de Blizzard. Warden anti-cheat activo. GPU-intensivo pero muy bien optimizado. DX12 recomendado.",
    fps_target: "144+",
    resolution: "1920x1080",
    tweaks: [
      "Warden: NUNCA modificar proceso de Battle.net",
      "Renderizado DX12 → Activado",
      "DLSS/FSR según GPU disponible",
      "Prioridad Overwatch.exe → Alta",
      "Shadow Detail → Low",
      "Reflection Quality → Low",
      "Local Fog Detail → Low",
      "Anti-Aliasing → FXAA (menos consumo)",
      "Reduce Buffering → Activado",
      "Triple Buffering → Desactivado",
      "NVIDIA Reflex → Activado + Boost si RTX",
      "High Quality Upsampling → Auto",
    ],
    settings: [
      { key: "Calidad Gráfica", value: "Medium" },
      { key: "Sombras", value: "Low" },
      { key: "Anti-Aliasing", value: "FXAA" },
      { key: "DLSS/FSR", value: "Quality si hay" },
      { key: "Frame Cap", value: "Sin límite" },
    ],
    expectedFpsGain: "+20-40 FPS",
    protected: ["Warden.dll", "Battle.net.exe"],
  },
  {
    id: "rust",
    name: "Rust",
    engine: "Unity 2019",
    genre: "Survival",
    anticheat: ["Easy Anti-Cheat", "FairFight"],
    color: "#CD4B2A",
    icon: "⚙️",
    banner: "https://cdn.akamai.steamstatic.com/steam/apps/252490/header.jpg",
    logo: "https://cdn.akamai.steamstatic.com/steam/apps/252490/logo.png",
    description: "Survival de Facepunch Studios. Muy exigente en CPU y RAM. Servidores con 200+ jugadores requieren i7+ y 16GB RAM.",
    fps_target: "60-100+",
    resolution: "1920x1080",
    tweaks: [
      "EAC: NUNCA modificar",
      "graphics.shaderlod 200 (consola)",
      "graphics.drawdistance 1000",
      "effects.maxgibs 0 (elimina gibs para FPS)",
      "Prioridad RustClient.exe → Alta",
      "HAGS → Activado",
      "RAM 16GB+ para servidores grandes",
      "CPU: priorizar frecuencia sobre núcleos",
      "Grass Displacement → Off",
      "Terrain Quality → 50-75",
      "Tree Quality → 50 para más FPS",
      "Shader Level → 400 (balance) vs 600 default",
    ],
    settings: [
      { key: "Gráficos", value: "Medium (balance)" },
      { key: "Hierba", value: "Desactivada" },
      { key: "Sombras", value: "Low" },
      { key: "Terreno", value: "50%" },
      { key: "Draw Distance", value: "1000" },
    ],
    expectedFpsGain: "+15-35 FPS",
    protected: ["EasyAntiCheat.exe"],
  },
  {
    id: "palworld",
    name: "Palworld",
    engine: "Unreal Engine 5",
    genre: "Survival / RPG",
    anticheat: ["Easy Anti-Cheat"],
    color: "#4CAF50",
    icon: "🌿",
    banner: "https://cdn.akamai.steamstatic.com/steam/apps/1623730/header.jpg",
    logo: "https://upload.wikimedia.org/wikipedia/en/thumb/e/eb/Palworld_cover_art.jpg/220px-Palworld_cover_art.jpg",
    description: "Survival RPG viral de Pocket Pair. UE5 sin Nanite — bien optimizado para midrange. EAC activo.",
    fps_target: "60-120+",
    resolution: "1920x1080",
    tweaks: [
      "EasyAntiCheat.exe: INTOCABLE",
      "DirectX 12 → Activado",
      "DLSS/FSR Quality si está disponible",
      "Shadow Quality → Low",
      "Foliage → Low",
      "Prioridad Palworld-Win64-Shipping.exe → Alta",
      "HAGS → Activado",
      "RAM 16GB para servidores multijugador",
      "Ambient Occlusion → Desactivado",
      "Motion Blur → Desactivado",
      "Anti-Aliasing → TAA o desactivado en GPUs potentes",
      "View Distance → 50% en PCs mid-range",
    ],
    settings: [
      { key: "Gráficos", value: "Medium" },
      { key: "Sombras", value: "Low" },
      { key: "Follaje", value: "Low" },
      { key: "DLSS/FSR", value: "Quality" },
      { key: "Motion Blur", value: "Desactivado" },
    ],
    expectedFpsGain: "+20-45 FPS",
    protected: ["EasyAntiCheat.exe"],
  },
  {
    id: "cyberpunk",
    name: "Cyberpunk 2077",
    engine: "REDengine 4",
    genre: "RPG / Acción",
    anticheat: ["Denuvo Anti-Tamper"],
    color: "#FCEE09",
    icon: "🌆",
    banner: "https://cdn.akamai.steamstatic.com/steam/apps/1091500/header.jpg",
    logo: "https://cdn.akamai.steamstatic.com/steam/apps/1091500/header.jpg",
    description: "Mega RPG de CD PROJEKT RED. Extremadamente exigente. RTX + DLSS 3/Frame Gen para máximo rendimiento con calidad visual.",
    fps_target: "60-120+",
    resolution: "1920x1080",
    tweaks: [
      "DLSS 3 / Frame Generation en RTX 40 series (+100% FPS)",
      "FSR 3 en AMD GPUs (+60% FPS)",
      "Crowd Density → Low/Off",
      "Volumetric Fog → Desactivado",
      "Mirror Quality → Low",
      "Screen Space Reflections → Off",
      "Prioridad Cyberpunk2077.exe → Alta",
      "DirectX 12 Ultimate recomendado",
      "VRAM 8GB+ para 1080p Ultra",
      "Path Tracing solo con RTX 40 series",
      "Shader pre-compilación: esperar en primer arranque",
    ],
    settings: [
      { key: "DLSS/FSR", value: "Quality" },
      { key: "Multitudes", value: "Low" },
      { key: "Niebla", value: "Off" },
      { key: "Reflejos", value: "Off" },
      { key: "Sombras", value: "Medium" },
    ],
    expectedFpsGain: "+25-60 FPS",
    protected: [],
  },
  {
    id: "helldivers2",
    name: "Helldivers 2",
    engine: "Autodesk Stingray",
    genre: "Shooter Cooperativo",
    anticheat: ["Easy Anti-Cheat", "nProtect GameGuard"],
    color: "#FFCC00",
    icon: "🪖",
    banner: "https://cdn.akamai.steamstatic.com/steam/apps/553850/header.jpg",
    logo: "https://cdn.akamai.steamstatic.com/steam/apps/553850/header.jpg",
    description: "Shooter co-op de Arrowhead. Muy CPU-dependiente. Los servidores necesitan buen upload. EAC activo — protegido.",
    fps_target: "60-120+",
    resolution: "1920x1080",
    tweaks: [
      "EasyAntiCheat.exe: INTOCABLE",
      "nProtect GameGuard: INTOCABLE",
      "Motion Blur → Desactivado",
      "Depth of Field → Desactivado",
      "SSR → Off",
      "VSync → Off",
      "Prioridad helldivers2.exe → Alta",
      "RAM 16GB+ recomendado para partidas 4P",
      "CPU frecuencia alta > núcleos",
    ],
    settings: [
      { key: "Blur", value: "Desactivado" },
      { key: "SSR", value: "Off" },
      { key: "VSync", value: "Off" },
      { key: "Textures", value: "High" },
      { key: "Sombras", value: "Medium" },
    ],
    expectedFpsGain: "+20-40 FPS",
    protected: ["EasyAntiCheat.exe", "GameGuard.exe"],
  },
  {
    id: "thefinals",
    name: "The Finals",
    engine: "Unreal Engine 5",
    genre: "Shooter Táctico",
    anticheat: ["Easy Anti-Cheat"],
    color: "#FF6B00",
    icon: "🎯",
    banner: "https://cdn.akamai.steamstatic.com/steam/apps/2073850/header.jpg",
    logo: "https://cdn.akamai.steamstatic.com/steam/apps/2073850/header.jpg",
    description: "Shooter destructible de Embark Studios. UE5 con física en tiempo real — muy exigente. EAC activo.",
    fps_target: "60-144+",
    resolution: "1920x1080",
    tweaks: [
      "EasyAntiCheat.exe: INTOCABLE",
      "Lumen → Desactivado (ahorra 30% GPU)",
      "Nanite → usar solo con GPU alta gama",
      "Motion Blur → Off",
      "DLSS/TSR/FSR → Quality",
      "Prioridad THEFINALS-Win64-Shipping.exe → Alta",
      "Destrucción global reduce FPS: reducir View Distance",
      "HAGS → Activado",
    ],
    settings: [
      { key: "Lumen", value: "Desactivado" },
      { key: "DLSS", value: "Quality" },
      { key: "View Distance", value: "Medium" },
      { key: "Destruction", value: "Medium" },
      { key: "Motion Blur", value: "Off" },
    ],
    expectedFpsGain: "+30-55 FPS",
    protected: ["EasyAntiCheat.exe"],
  },
  {
    id: "warframe",
    name: "Warframe",
    engine: "Evolution Engine",
    genre: "Shooter / RPG",
    anticheat: ["Easy Anti-Cheat"],
    color: "#1E90FF",
    icon: "⚡",
    banner: "https://cdn.akamai.steamstatic.com/steam/apps/230410/header.jpg",
    logo: "https://cdn.akamai.steamstatic.com/steam/apps/230410/header.jpg",
    description: "Free-to-play de Digital Extremes. Bien optimizado. Nueva Guerra y Duviri son los mapas más pesados.",
    fps_target: "144-240+",
    resolution: "1920x1080",
    tweaks: [
      "EasyAntiCheat.exe: INTOCABLE",
      "Dynamic Resolution → Desactivado",
      "Volumetric Lighting → Off en GPUs mid-range",
      "Ambient Occlusion → Off",
      "Prioridad Warframe.x64.exe → Alta",
      "RAM 8GB suficiente, 16GB ideal para misiones largas",
      "Display Mode → Fullscreen Exclusive",
      "Multi-Thread Rendering → ON",
    ],
    settings: [
      { key: "Resolución Dinámica", value: "Off" },
      { key: "Iluminación Vol.", value: "Off" },
      { key: "AO", value: "Off" },
      { key: "Modo Display", value: "Fullscreen" },
      { key: "Multi-Thread", value: "ON" },
    ],
    expectedFpsGain: "+25-50 FPS",
    protected: ["EasyAntiCheat.exe"],
  },
  {
    id: "rocketleague",
    name: "Rocket League",
    engine: "Unreal Engine 3",
    genre: "Sports / Competitivo",
    anticheat: ["Easy Anti-Cheat"],
    color: "#FF4500",
    icon: "🚗",
    banner: "https://cdn.akamai.steamstatic.com/steam/apps/252950/header.jpg",
    logo: "https://cdn.akamai.steamstatic.com/steam/apps/252950/header.jpg",
    description: "Soccer con autos de Psyonix/Epic. Juego esports popular — objetivo 250 FPS para HDMI/HDMI. EAC activo.",
    fps_target: "250-300+",
    resolution: "1920x1080",
    tweaks: [
      "EasyAntiCheat.exe: INTOCABLE",
      "Display Mode → Fullscreen Exclusive",
      "VSync → Off",
      "Motion Blur → Off",
      "Render Quality → Performance",
      "Ambient Occlusion → Off",
      "Depth of Field → Off",
      "Max FPS → 250+ (desbloquear en config)",
      "Prioridad RocketLeague.exe → Alta",
    ],
    settings: [
      { key: "Render Quality", value: "Performance" },
      { key: "Motion Blur", value: "Off" },
      { key: "AO", value: "Off" },
      { key: "VSync", value: "Off" },
      { key: "Max FPS", value: "Desbloqueado" },
    ],
    expectedFpsGain: "+50-120 FPS",
    protected: ["EasyAntiCheat.exe"],
  },
  {
    id: "deadbydaylight",
    name: "Dead by Daylight",
    engine: "Unreal Engine 4",
    genre: "Horror Asimétrico",
    anticheat: ["Easy Anti-Cheat"],
    color: "#CC0000",
    icon: "🔦",
    banner: "https://cdn.akamai.steamstatic.com/steam/apps/381210/header.jpg",
    logo: "https://cdn.akamai.steamstatic.com/steam/apps/381210/header.jpg",
    description: "Horror 1v4 de Behaviour Interactive. Muy CPU-dependiente por la IA del asesino y pathfinding. EAC activo.",
    fps_target: "60-120+",
    resolution: "1920x1080",
    tweaks: [
      "EasyAntiCheat.exe: INTOCABLE",
      "Motion Blur → Off",
      "Ambient Occlusion → Off",
      "VSync → Off",
      "Texture Quality → Medium",
      "Anti-Aliasing → TAA o Off",
      "Prioridad DeadByDaylight-Win64-Shipping.exe → Alta",
      "HAGS → Activado",
      "CPU frecuencia alta para IA del asesino",
    ],
    settings: [
      { key: "Motion Blur", value: "Off" },
      { key: "AO", value: "Off" },
      { key: "Texturas", value: "Medium" },
      { key: "Anti-Aliasing", value: "Off" },
      { key: "VSync", value: "Off" },
    ],
    expectedFpsGain: "+20-45 FPS",
    protected: ["EasyAntiCheat.exe"],
  },
  {
    id: "seaofthieves",
    name: "Sea of Thieves",
    engine: "Unreal Engine 4",
    genre: "Aventura / Piratas",
    anticheat: ["Easy Anti-Cheat", "VAC"],
    color: "#00CED1",
    icon: "⚓",
    banner: "https://cdn.akamai.steamstatic.com/steam/apps/1172620/header.jpg",
    logo: "https://cdn.akamai.steamstatic.com/steam/apps/1172620/header.jpg",
    description: "Aventura pirata de Rare. Excelente optimización — corre bien en gama media. El océano es GPU-intensivo.",
    fps_target: "60-120+",
    resolution: "1920x1080",
    tweaks: [
      "EasyAntiCheat.exe: INTOCABLE",
      "Motion Blur → Off",
      "Water Quality → Medium (la más exigente)",
      "Volumetric Lighting → Off",
      "Shadows → Low",
      "Prioridad SoTGame-Win64-Shipping.exe → Alta",
      "DLSS/FSR si disponible",
      "HAGS → Activado",
    ],
    settings: [
      { key: "Agua", value: "Medium" },
      { key: "Sombras", value: "Low" },
      { key: "Motion Blur", value: "Off" },
      { key: "Vol. Lighting", value: "Off" },
      { key: "DLSS", value: "Quality" },
    ],
    expectedFpsGain: "+25-50 FPS",
    protected: ["EasyAntiCheat.exe"],
  },
  {
    id: "hogwartslegacy",
    name: "Hogwarts Legacy",
    engine: "Unreal Engine 4",
    genre: "RPG / Aventura",
    anticheat: ["Denuvo Anti-Tamper"],
    color: "#8B6914",
    icon: "⚡",
    banner: "https://cdn.akamai.steamstatic.com/steam/apps/990080/header.jpg",
    logo: "https://cdn.akamai.steamstatic.com/steam/apps/990080/header.jpg",
    description: "RPG de Hogwarts de Avalanche. Extremadamente CPU-limitado. Hogsmeade y el castillo son las zonas más pesadas.",
    fps_target: "60-100+",
    resolution: "1920x1080",
    tweaks: [
      "Motion Blur → Off",
      "Depth of Field → Off",
      "Ray Tracing → Off en gama media",
      "Foliage → Medium",
      "DLSS/FSR → Quality o Balanced",
      "Prioridad HogwartsLegacy.exe → Alta",
      "CPU con 8+ núcleos recomendado",
      "RAM 16GB+ para cargas rápidas",
      "Shader compilation al primer arranque: esperar",
    ],
    settings: [
      { key: "Ray Tracing", value: "Off" },
      { key: "Motion Blur", value: "Off" },
      { key: "DLSS/FSR", value: "Quality" },
      { key: "Follaje", value: "Medium" },
      { key: "Sombras", value: "Medium" },
    ],
    expectedFpsGain: "+20-40 FPS",
    protected: [],
  },
  {
    id: "battlefield2042",
    name: "Battlefield 2042",
    engine: "Frostbite",
    genre: "Shooter Táctico",
    anticheat: ["Easy Anti-Cheat"],
    color: "#1E5799",
    icon: "💣",
    banner: "https://cdn.akamai.steamstatic.com/steam/apps/1517290/header.jpg",
    logo: "https://cdn.akamai.steamstatic.com/steam/apps/1517290/header.jpg",
    description: "Shooter masivo de DICE/EA. Frostbite Engine muy CPU-dependiente. 128 jugadores requieren CPU fuerte (i7/Ryzen 7+).",
    fps_target: "60-144+",
    resolution: "1920x1080",
    tweaks: [
      "EasyAntiCheat.exe: INTOCABLE",
      "Future Frame Rendering → Activado (+FPS)",
      "Motion Blur → Off",
      "Ambient Occlusion → SSAO (no HBAO)",
      "Post Processing → Low",
      "Prioridad BF2042.exe → Alta",
      "CPU: 8 núcleos mínimo para 128p",
      "RAM 16GB+ para textures streaming",
      "DLSS/FSR → Quality",
    ],
    settings: [
      { key: "Motion Blur", value: "Off" },
      { key: "Post Process", value: "Low" },
      { key: "AO", value: "SSAO" },
      { key: "DLSS/FSR", value: "Quality" },
      { key: "Future Frame", value: "ON" },
    ],
    expectedFpsGain: "+20-45 FPS",
    protected: ["EasyAntiCheat.exe"],
  },
  {
    id: "lostark",
    name: "Lost Ark",
    engine: "Unreal Engine 3",
    genre: "MMORPG / ARPG",
    anticheat: ["Easy Anti-Cheat", "Xigncode3"],
    color: "#DAA520",
    icon: "⚔️",
    banner: "https://cdn.akamai.steamstatic.com/steam/apps/1599340/header.jpg",
    logo: "https://cdn.akamai.steamstatic.com/steam/apps/1599340/header.jpg",
    description: "MMORPG coreano de Smilegate. Muy CPU-limitado. Las raids con 8 jugadores saturan el single thread. Doble anti-cheat.",
    fps_target: "60-144+",
    resolution: "1920x1080",
    tweaks: [
      "EasyAntiCheat.exe: INTOCABLE",
      "Xigncode3: INTOCABLE",
      "Shadow Quality → Low",
      "Shadow Distance → Low",
      "Foliage → Low",
      "Ambient Occlusion → Off",
      "Prioridad LOSTARK.exe → Alta",
      "CPU single-thread fuerte (Intel > AMD en este juego)",
      "RAM 16GB para raids sin stutters",
    ],
    settings: [
      { key: "Sombras", value: "Low" },
      { key: "Follaje", value: "Low" },
      { key: "AO", value: "Off" },
      { key: "Personajes", value: "Medium" },
      { key: "Efectos", value: "Low" },
    ],
    expectedFpsGain: "+20-40 FPS",
    protected: ["EasyAntiCheat.exe", "Xigncode3.exe"],
  },
  {
    id: "escapetarkov",
    name: "Escape from Tarkov",
    engine: "Unity",
    genre: "FPS / Extraction Shooter",
    anticheat: ["BattlEye"],
    color: "#556B2F",
    icon: "🎒",
    banner: "https://upload.wikimedia.org/wikipedia/en/thumb/0/0d/Escape_from_Tarkov_game_logo.jpg/460px-Escape_from_Tarkov_game_logo.jpg",
    logo: "https://upload.wikimedia.org/wikipedia/en/thumb/0/0d/Escape_from_Tarkov_game_logo.jpg/300px-Escape_from_Tarkov_game_logo.jpg",
    description: "Extraction shooter hardcore de Battlestate. Unity sin optimizar — requiere SSD NVMe y RAM rápida. BattlEye activo.",
    fps_target: "60-120+",
    resolution: "1920x1080",
    tweaks: [
      "BattlEye.exe: INTOCABLE",
      "SSD NVMe OBLIGATORIO — reduce stutters de carga",
      "RAM 16GB (32GB ideal para mapas grandes)",
      "Textures → Medium (no Ultra por VRAM)",
      "Shadows → Low",
      "LOD → 2-3",
      "Anti-Aliasing → Off en gama media",
      "Prioridad EscapeFromTarkov.exe → Alta",
      "Preload Terrain Meshes → ON",
      "RAM Cleaner integrado en ajustes del juego",
    ],
    settings: [
      { key: "Texturas", value: "Medium" },
      { key: "Sombras", value: "Low" },
      { key: "Anti-Aliasing", value: "Off" },
      { key: "LOD", value: "2" },
      { key: "Preload Terrain", value: "ON" },
    ],
    expectedFpsGain: "+20-50 FPS",
    protected: ["BattlEye.exe", "BEService.exe"],
  },
  {
    id: "huntshowdown",
    name: "Hunt: Showdown 1896",
    engine: "CryEngine",
    genre: "Horror / Battle Royale",
    anticheat: ["Easy Anti-Cheat"],
    color: "#8B4513",
    icon: "🏹",
    banner: "https://cdn.akamai.steamstatic.com/steam/apps/594650/header.jpg",
    logo: "https://cdn.akamai.steamstatic.com/steam/apps/594650/logo.png",
    description: "Battle royale de horror de Crytek. CryEngine bien optimizado. Los mapas pantanosos son los más exigentes en GPU.",
    fps_target: "60-144+",
    resolution: "1920x1080",
    tweaks: [
      "EasyAntiCheat.exe: INTOCABLE",
      "Shadows → Low",
      "Vegetation → Medium",
      "Particles → Medium",
      "Motion Blur → Off",
      "Anti-Aliasing → Temporal AA",
      "Prioridad HuntGame.exe → Alta",
      "HAGS → Activado",
      "Sharpening → ON (mejora visibilidad)",
    ],
    settings: [
      { key: "Sombras", value: "Low" },
      { key: "Vegetación", value: "Medium" },
      { key: "Motion Blur", value: "Off" },
      { key: "Anti-Aliasing", value: "TAA" },
      { key: "Sharpening", value: "ON" },
    ],
    expectedFpsGain: "+20-40 FPS",
    protected: ["EasyAntiCheat.exe"],
  },
  {
    id: "dota2",
    name: "Dota 2",
    engine: "Source 2",
    genre: "MOBA Estrategia",
    anticheat: ["VAC"],
    color: "#c23c2a",
    icon: "🛡️",
    banner: "https://cdn.akamai.steamstatic.com/steam/apps/570/header.jpg",
    logo: "https://cdn.cloudflare.steamstatic.com/steamcommunity/public/images/apps/570/0bbb74f7f339925d9bd88b93e9e77d6e2e44a5e6.jpg",
    description: "MOBA de Valve en Source 2. Las partidas de late game con efectos de partículas masivos son muy exigentes en GPU. Optimizar para mantener 60+ fps estables en teamfights.",
    fps_target: "60-144+",
    resolution: "1920x1080",
    tweaks: [
      "VAC: NUNCA modificar archivos del juego",
      "launch options: -high -nojoy -noipx -novid -map dota",
      "Renderer → DirectX 11 (más estable que DX12 en Dota)",
      "Prioridad dota2.exe → Alta",
      "V-Sync → Off (activa FPS cap a 144 si tienes pantalla 144Hz)",
      "Shadow Quality → Low en teamfights",
      "Particles → Medium (reducir en late game)",
      "MSAA → Off, usar filtro anisotrópico x8 en driver",
      "Specular → Off",
      "HAGS → Activado",
      "Nagle Algorithm → Off para menor latencia al servidor de Valve",
      "DNS → 1.1.1.1 para servers EU/NA",
    ],
    settings: [
      { key: "Renderizador", value: "DirectX 11" },
      { key: "Calidad Sombras", value: "Low" },
      { key: "Partículas", value: "Medium" },
      { key: "Reflexiones", value: "Off" },
      { key: "Anti-Aliasing", value: "Off" },
      { key: "V-Sync", value: "Off" },
    ],
    expectedFpsGain: "+25-45 FPS",
    protected: ["steamservice.exe"],
  },
  {
    id: "r6siege",
    name: "Rainbow Six Siege",
    engine: "AnvilNext 2.0",
    genre: "FPS Táctico",
    anticheat: ["BattlEye"],
    color: "#2a80b9",
    icon: "🪟",
    banner: "https://cdn.akamai.steamstatic.com/steam/apps/359550/header.jpg",
    logo: "https://cdn.cloudflare.steamstatic.com/steamcommunity/public/images/apps/359550/3e9e73de00b6d1fbbae61a88fc1b9ddf5b6fae3e.jpg",
    description: "FPS táctico de Ubisoft muy exigente con CPU. El sistema de destrucción física requiere mucho procesamiento. La IA de Vulture usa BattlEye kernel-level.",
    fps_target: "144-240+",
    resolution: "1920x1080",
    tweaks: [
      "BattlEye.exe: INTOCABLE — kernel-level driver",
      "Renderer → Vulkan (mejor rendimiento en Siege moderno)",
      "Prioridad RainbowSix.exe → Alta",
      "Texture Quality → Alto (no impacta FPS, solo VRAM)",
      "Shadows → Low o Medium",
      "LOD → Alto (mejor visibilidad de operadores)",
      "Lens Effects → Off (elimina bloom y blur innecesario)",
      "Sharpening → Alto para mejor detección de enemigos",
      "V-Sync → Off, Frame cap a 240 si tienes pantalla 240Hz",
      "FOV → 90 para mejor visión periférica",
      "Timer Resolution → 0.5ms para menor latencia de input",
      "Modo Alto Rendimiento en plan de energía",
    ],
    settings: [
      { key: "Renderer", value: "Vulkan" },
      { key: "Sombras", value: "Low" },
      { key: "Sharpening", value: "Alto" },
      { key: "Efectos de Lente", value: "Off" },
      { key: "V-Sync", value: "Off" },
      { key: "FOV", value: "90" },
    ],
    expectedFpsGain: "+30-60 FPS",
    protected: ["BattlEye.exe", "BEService.exe"],
  },
  {
    id: "overwatch2",
    name: "Overwatch 2",
    engine: "Proprietary (Blizzard)",
    genre: "Hero Shooter",
    anticheat: ["Warden (Blizzard)"],
    color: "#f99e1a",
    icon: "🤖",
    banner: "https://cdn.akamai.steamstatic.com/steam/apps/2357570/header.jpg",
    logo: "https://cdn.cloudflare.steamstatic.com/steamcommunity/public/images/apps/2357570/86e4c67d29fa3e3d8cc59e5e7de48b9fbb98a31d.jpg",
    description: "Hero shooter F2P de Blizzard. Motor propietario bien optimizado. El mayor impacto en FPS viene de las habilidades con partículas masivas (ultimate de Mei, Sigma, etc.).",
    fps_target: "144-300+",
    resolution: "1920x1080",
    tweaks: [
      "Warden (anti-cheat Blizzard): NO tocar procesos de Battle.net",
      "Renderizador → DirectX 12 (mejor en GPUs modernas)",
      "Prioridad Overwatch2.exe → Alta",
      "High Quality Upsampling → On (DLSS/FSR si disponible)",
      "Dynamic Render Scale → 100% fijo (evita variación de FPS)",
      "Shadow Detail → Low o Medium",
      "Local Fog Detail → Low",
      "Effects Detail → Medium (más bajo = más FPS en teamfights)",
      "V-Sync → Off",
      "Refraction Quality → Low",
      "Anti-Aliasing → Off o FXAA",
      "HAGS → Activado para lower frame times",
    ],
    settings: [
      { key: "Renderer", value: "DirectX 12" },
      { key: "Shadow Detail", value: "Low" },
      { key: "Effects Detail", value: "Medium" },
      { key: "Anti-Aliasing", value: "Off" },
      { key: "V-Sync", value: "Off" },
      { key: "Dynamic Render Scale", value: "100% fijo" },
    ],
    expectedFpsGain: "+20-50 FPS",
    protected: ["Battle.net.exe", "Agent.exe"],
  },
  {
    id: "gtav",
    name: "GTA V / GTA Online",
    engine: "RAGE",
    genre: "Open World / Online",
    anticheat: ["Rockstar Anticheat (RGSC)"],
    color: "#1baf64",
    icon: "🌆",
    banner: "https://cdn.akamai.steamstatic.com/steam/apps/271590/header.jpg",
    logo: "https://cdn.cloudflare.steamstatic.com/steamcommunity/public/images/apps/271590/84b3d1a730ad89434fdbdad7c93e4e4d3a6f9c6f.jpg",
    description: "GTA V es uno de los juegos PC más exigentes si no se configura bien. GTA Online sufre lag adicional por el sistema P2P. El motor RAGE se beneficia enormemente del ajuste de distancia de visión y sombras.",
    fps_target: "60-144+",
    resolution: "1920x1080",
    tweaks: [
      "Rockstar Game Services: no interferir con RGSC.exe",
      "Render Quality → Normal (la más eficiente)",
      "Distancia de visión → 50-60 (el mayor culpable de bajo FPS)",
      "Detalle de la distancia → 30-50",
      "Sombras → Normal (no usar Muy Alto)",
      "Calidad de texturas → Normal o Alto (según VRAM)",
      "Anti-Aliasing → FXAA o MSAA x2",
      "TXAA → Off (causa blur)",
      "Shader Quality → Normal",
      "Grass → Normal",
      "V-Sync → Off (desactivar en opciones avanzadas)",
      "Frame Scaling → 1x (OFF)",
      "Prioridad GTA5.exe → Alta",
      "HAGS → Activado",
    ],
    settings: [
      { key: "Distancia Visión", value: "50-60" },
      { key: "Sombras", value: "Normal" },
      { key: "Calidad Render", value: "Normal" },
      { key: "Anti-Aliasing", value: "FXAA" },
      { key: "V-Sync", value: "Off" },
      { key: "Frame Scaling", value: "Off (1x)" },
    ],
    expectedFpsGain: "+30-70 FPS",
    protected: ["RGSC.exe", "RockstarService.exe"],
  },
];

export const getGame = (id) => GAMES.find(g => g.id === id);
